### ISSUE TITLE
OSError on Mac OS X 10. 11

### ISSUE THREAD

**Issue by QilinGu** [Google1234/Information_retrieva_Projectl-#15]
想试着在Mac上跑一下，结果报错了，有可能是OS X的原因：
python main.py
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    word2vec=Word2Vec.WORD2VEC("../",'../data/'+config.word2Vec_filename)
  File "../word2Vec/word2vec.py", line 15, in __init__
    self.word2vec_distance = cdll.LoadLibrary(so_filename+'word2Vec/distance.so')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(../word2Vec/distance.so, 6): image not found

**Comment by QilinGu** [comment]
我小白了, .so 文件没法在Mac上用，我装个Virtualbox吧。

**Comment by hatleon** [comment]
你好，问一下，作者没有.so文件，我按照word2vec.py文件里的命令编译了.o文件生成了.so文件。但是运行报oserror ELF header错误，运行环境vmware+ubuntu14+pycharm2017社区版自带的python2.7，谢谢。
