### ISSUE TITLE
爬取网页数目足够时，没能及时停止爬虫

### ISSUE THREAD

**Issue by Google1234** [Google1234/Information_retrieva_Projectl-#4]
http://www.sharejs.com/codes/python/8808

**Comment by Google1234** [comment]
```
def parse(self,response):
    if self.web_id>self.crawl_number:
        if self.has_terminated==False:
            self.write_block_data.close()
            self.write_block_crawlwd_weburl.close()
            del self.write_block_crawlwd_weburl,self.write_block_data
            self.has_terminated==True
```

2016-05-22 01:26:58 [scrapy] ERROR: Spider error processing <GET http://news.163.com/rank/> (referer: http://news.163.com/)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 28, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 54, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Python\Information_retrieva_Projectl-\crawl\spiders\netease_spider.py", line 59, in parse
    del self.write_block_crawlwd_weburl,self.write_block_data
AttributeError: write_block_crawlwd_weburl
